### ISSUE TITLE
Make skrifa optional

### ISSUE THREAD

**Issue by IvanUkhov** [googlefonts/shaperglot#104]
Would it be of interest to hide the parser behind a feature and make it possible to instantiate the checker by providing it all the necessary pieces of information, such as a character map and feature names, directly? The goal is to reduce the number of dependencies and leave it up to the end user how the parsing is done.

**Comment by simoncozens** [comment]
I'm not sure that's possible. It's called "shaper"glot for a reason. :-) How would you handle the shaping?

**Comment by IvanUkhov** [comment]
I suppose there are two font parsers involved: read-fonts and ttf-parser. The latter is part of harfbuzz, and it is indeed needed for shaping. The former, however, is used for extracting the glyph names, features, and character mapping, which can be done ahead of time and potentially by other parsers. I opened a PR to illustrate the idea. Again, if there is interest from your side.

**Comment by simoncozens** [comment]
(The aim of harfruzz is to kick out ttf-parser and replace it with read-fonts, so we have read-fonts on both sides. But I'm not seeing a lot of progress towards that aim right now.)
