### ISSUE TITLE
Mozilla Firefox can't set properties on CSSFontFaceRule declarations

### ISSUE THREAD

**Issue by moyogo** [googlefonts/shaperglot#105]
Mozilla Firefox is having the following error since today when a font file is dropped in.
<pre>
Layout was forced before the page was fully loaded. If stylesheets are not yet loaded this may cause a flash of unstyled content. [ThumbnailsChild.sys.mjs:26:13](resource://gre/actors/ThumbnailsChild.sys.mjs)
Loading the module [webworker.js:4:11](webpack://create-wasm-app/./webworker.js?)
Loaded [webworker.js:6:11](webpack://create-wasm-app/./webworker.js?)
Drop! [index.js:313:13](webpack://create-wasm-app/./index.js?)
Uncaught DOMException: CSSStyleDeclaration.setProperty: Can't set properties on CSSFontFaceRule declarations
    dropFile webpack://create-wasm-app/./index.js?:57
    <anonymous> webpack://create-wasm-app/./index.js?:321
    jQuery 2
        dispatch
        handle
</pre>

**Comment by simoncozens** [comment]
The Firefox bug tracking this is https://bugzilla.mozilla.org/show_bug.cgi?id=1736640.
