### ISSUE TITLE
Bulk run giving TypeError after unencoded_variants test added

### ISSUE THREAD

**Issue by NeilSureshPatel** [googlefonts/shaperglot#12]
I was trying to test out some new gflang data sets and after the `unencoded-variants` was added the bulk run errors out with the following error:

```
Traceback (most recent call last):
  File "/home/neilspatel/Shaperglot/shaperglot-env/bulk-sg-run.py", line 133, in <module>
    main()
  File "/home/neilspatel/Shaperglot/shaperglot-env/bulk-sg-run.py", line 123, in main
    summarize(tag, fontname, this_tag_results)
  File "/home/neilspatel/Shaperglot/shaperglot-env/bulk-sg-run.py", line 69, in summarize
    for code, failure in results:
TypeError: cannot unpack non-iterable Message object
```

I have been chasing my tail trying to understand why this would happen. I am not sure if I am missing something obvious. What is odd is that this is occurring even if I am not using the new check. If I remove all shaperglot profiles and run `bulk-sg-run.py` on a single font and a single language tag, I still get the error. This should be only running the default `no_orphaned_marks` and `orthographies` checks so I don't understand how adding the new check would cause this since nothing else was changed.

**Comment by simoncozens** [comment]
My fault, I changed the Message interface and so things using shaperglot will break if they're not updated. We should probably put the "bulk-sg-run" script into this repo while the shaperglot API is in flux, so that it can be updated too.
