### ISSUE TITLE
Undeclared dependency on PyYAML

### ISSUE THREAD

**Issue by RickyDaMa** [googlefonts/shaperglot#42]
https://github.com/googlefonts/shaperglot/blob/21214998b569ae7c426405152f331579837b84c0/shaperglot/languages.py#L8

This uses PyYAML if I'm not mistaken, which isn't included as a dependency in `pyproject.toml`

With a fresh venv, doing `pip install shaperglot` gets me a `ModuleNotFoundError: No module named 'yaml'` error

**Comment by simoncozens** [comment]
I am constantly amazed by the things that aren't in the Python standard library.
