### ISSUE TITLE
Alef Maksura

### ISSUE THREAD

**Issue by simoncozens** [googlefonts/shaperglot#86]
@yanone reported an issue with the generated rules for ALEF MAKSURA, issue to track that.

**Comment by yanone** [comment]
```
           .medi version of ARABIC LETTER ALEF MAKSURA; both buffers returned    uni0649=1+1071                                                         
           space=1+0                                                                                                                                    
           .init version of ARABIC LETTER ALEF MAKSURA; both buffers returned    uni0649=0+1071                                                         
           space=0+0                                                                                                                                    
```

Specifically, the letter is reported as dual-joining by `youseedee` but only exists as right-joining. (The legacy characters also only exist as isolated and right-joining).

**Comment by moyogo** [comment]
This issue doesn't seem right.

**Comment by moyogo** [comment]
> Specifically, the letter is reported as dual-joining by youseedee but in reality only exists as right-joining. (The legacy fully-encoded characters also only exist as isolated and right-joining).

@yanone Uighur uses 0649 dual-joining. Do you mean something more specific?

**Comment by yanone** [comment]
No, this is the answer. I wasn't aware of that and got confused further by the legacy right-joining-only encoded characters.

It means that we can ignore the reports at least for Arabic/Farsi/Urdu fonts at our discretion, and otherwise insist on it to function in full for fonts with wider language support.

Thank you. I'm closing this.
